#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL

// Scene
#define SCENE_POSITION_ATTRIB_LOCATION 0
#define SCENE_TEXCOORD_ATTRIB_LOCATION 1
#define SCENE_NORMAL_ATTRIB_LOCATION 2
//Tangent array
#define SCENE_TANGENT_ATTRIB_LOCATION 3

#define SCENE_DIFFUSE_MAP_TEXTURE_BINDING 0

//added shader
#define SCENE_SHADOW_MAP_TEXTURE_BINDING 1
//alpha map
#define SCENE_ALPHA_MAP_TEXTURE_BINDING 2
//specular map
#define SCENE_SPECULAR_MAP_TEXTURE_BINDING 3
//bump map
#define SCENE_BUMP_MAP_TEXTURE_BINDING 4
//skybox
#define SCENE_SKYBOX_TEXTURE_BINDING 5
//bloom
#define SCENE_BIGHT_MAP_TEXTURE_BINDING 6
//imgui debug window
#define DEPTHVIS_DEPTH_MAP_TEXTURE_BINDING 0

#endif // PREAMBLE_GLSL